config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'
  resources :hotels, only: [:index] do
    resources :booking, only: [:new, :create] do
      collection do
        get :confirmed
      end
    end
  end
end

app/models/booking.rb
class Booking < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/booking_controller.rb
class BookingController < ApplicationController
  def create
    BookingService.create(params[:hotel_id], booking_params)
    # TODO: Create Booking
    redirect_to action: :confirmed
  end

private
  def booking_params
    params.require(:booking).permit(:name, :from, :to)
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  def index
    @hotels = HotelSearchService.near(search_hotels_params)
  end

private
  
  def search_hotels_params
    params.permit(:lat, :lon)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/booking/confirmed.html.haml
%p
  Booking Requested Successfully.

app/views/booking/new.html.haml
= form_for :booking, url: hotel_booking_index_path(params[:hotel_id]) do |f|
  = f.label :name
  = f.text_field :name
  = f.label :from
  = f.text_field :from
  = f.label :to
  = f.text_field :to
  = f.submit "Request Booking"

app/views/hotels/index.html.haml
%p
  Results found: 
.results
  - if @hotels.any?
    %table.hotel-list-table
      %thead
        %tr
          %th Name
      %tbody
        - @hotels.each do |hotel|
          %tr
            %td= hotel.name
          %tr
            %td= link_to "Book Hotel", new_hotel_booking_path(hotel.place_id)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ConichiBooking
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/pages/index.html.haml
= button_to('Search for Hotels', hotels_path, method: :get)